var CONSTANTS = require('./constants');
var mysql = require('mysql');

var connection = mysql.createConnection({
  host: 'localhost',
  user: process.env.SQL_USER || 'root',
  password: process.env.SQL_PASSWORD || '',
});


const DATABASE = CONSTANTS.DATABASE.NAME

const CREATE_DATABASE_QUERY = `CREATE DATABASE ${DATABASE}`

const ID_QUERY = 'id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY'
const CREATED_AT_QUERY = 'created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
const UPDATED_AT_QUERY = 'updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'
const IMAGE_ID_QUERY = `${CONSTANTS.DATABASE.POSTS_TABLE.COLUMNS.IMAGE} INT(6) NULL`
const TITLE_QUERY = `${CONSTANTS.DATABASE.POSTS_TABLE.COLUMNS.TITLE} VARCHAR(50)`
const CONTENT_QUERY = `${CONSTANTS.DATABASE.POSTS_TABLE.COLUMNS.CONTENT} VARCHAR(1000)`
const NAME_QUERY = `${CONSTANTS.DATABASE.IMAGE_TABLE.COLUMNS.NAME} VARCHAR(33)`

const POSTS_TABLE_CREATE_QUERY = `CREATE TABLE ${DATABASE}.${CONSTANTS.DATABASE.POSTS_TABLE.NAME} (${ID_QUERY}, ${IMAGE_ID_QUERY}, ${TITLE_QUERY}, ${CONTENT_QUERY}, ${CREATED_AT_QUERY}, ${UPDATED_AT_QUERY})`

const IMAGES_TABLE_CREATE_QUERY = `CREATE TABLE ${DATABASE}.${CONSTANTS.DATABASE.IMAGE_TABLE.NAME} (${ID_QUERY}, ${NAME_QUERY}, ${CREATED_AT_QUERY})`

connection.query(CREATE_DATABASE_QUERY)
connection.query(IMAGES_TABLE_CREATE_QUERY)
connection.query(POSTS_TABLE_CREATE_QUERY)

connection.end()